<h1>Importing Libraries

In [934]:
import pandas as pd
import numpy as np
import matplotlib as mlt
import statistics as stat
import seaborn as sns
from sklearn import preprocessing
import os
import datetime as dt
from operator import attrgetter
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

<h3>Importing Dataset

In [935]:
data = pd.read_csv('./Odataset.csv')

<h3>Droping Constant columns

In [936]:
data.head()

,business_code,cust_number,name_customer,clear_date,buisness_year,doc_id,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,posting_id,area_business,total_open_amount,baseline_create_date,cust_payment_terms,invoice_id,isOpen
0,U001,200769623,WAL-MAR corp,11-02-2020 00:00,2020,1930438491,26-01-2020,20200125,20200126,20200210,USD,RV,1,NaN,54273.28,20200126,NAH4,1.930438e+09,0
1,U001,200980828,BEN E,08-08-2019 00:00,2019,1929646410,22-07-2019,20190722,20190722,20190811,USD,RV,1,NaN,79656.60,20190722,NAD1,1.929646e+09,0
2,U001,200792734,MDV/ trust,30-12-2019 00:00,2019,1929873765,14-09-2019,20190914,20190914,20190929,USD,RV,1,NaN,2253.86,20190914,NAA8,1.929874e+09,0
3,CA02,140105686,SYSC llc,NaN,2020,2960623488,30-03-2020,20200330,20200330,20200410,CAD,RV,1,NaN,3299.70,20200331,CA10,2.960623e+09,1
4,U001,200769623,WAL-MAR foundation,25-11-2019 00:00,2019,1930147974,13-11-2019,20191113,20191113,20191128,USD,RV,1,NaN,33133.29,20191113,NAH4,1.930148e+09,0

In [937]:
data.drop(['doc_id','posting_id','area_business','invoice_id'],axis=1,inplace=True)

In [938]:
data.drop(['buisness_year'],axis=1,inplace=True)

In [939]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   business_code           50000 non-null  object
 1   cust_number             50000 non-null  object
 2   name_customer           50000 non-null  object
 3   clear_date              40000 non-null  object
 4   posting_date            50000 non-null  object
 5   document_create_date    50000 non-null  int64
 6   document_create_date.1  50000 non-null  int64
 7   due_in_date             50000 non-null  int64
 8   invoice_currency        50000 non-null  object
 9   document type           50000 non-null  object
 10  total_open_amount       50000 non-null  float64
 11  baseline_create_date    50000 non-null  int64
 12  cust_payment_terms      50000 non-null  object
 13  isOpen                  50000 non-null  int64
dtypes: float64(1), int64(5), object(8)
memory usage: 5.3+ MB

In [940]:
data.nunique()

business_code                 6
cust_number                1099
name_customer              4197
clear_date                  403
posting_date                506
document_create_date        507
document_create_date.1      506
due_in_date                 547
invoice_currency              2
document type                 2
total_open_amount         44349
baseline_create_date        506
cust_payment_terms           74
isOpen                        2
dtype: int64

In [941]:
data

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,total_open_amount,baseline_create_date,cust_payment_terms,isOpen
0,U001,200769623,WAL-MAR corp,11-02-2020 00:00,26-01-2020,20200125,20200126,20200210,USD,RV,54273.28,20200126,NAH4,0
1,U001,200980828,BEN E,08-08-2019 00:00,22-07-2019,20190722,20190722,20190811,USD,RV,79656.60,20190722,NAD1,0
2,U001,200792734,MDV/ trust,30-12-2019 00:00,14-09-2019,20190914,20190914,20190929,USD,RV,2253.86,20190914,NAA8,0
3,CA02,140105686,SYSC llc,NaN,30-03-2020,20200330,20200330,20200410,CAD,RV,3299.70,20200331,CA10,1
4,U001,200769623,WAL-MAR foundation,25-11-2019 00:00,13-11-2019,20191113,20191113,20191128,USD,RV,33133.29,20191113,NAH4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U001,200561861,CO corporation,NaN,21-04-2020,20200417,20200421,20200506,USD,RV,3187.86,20200421,NAA8,1
49996,U001,200769623,WAL-MAR co,03-09-2019 00:00,15-08-2019,20190814,20190815,20190830,USD,RV,6766.54,20190815,NAH4,0
49997,U001,200772595,SAFEW associates,05-03-2020 00:00,19-02-2020,20200218,20200219,20200305,USD,RV,6120.86,20200219,NAA8,0
49998,U001,200726979,BJ'S llc,12-12-2019 00:00,27-11-2019,20191126,20191127,20191212,USD,RV,63.48,20191127,NAA8,0
49999,U001,200020431,DEC corp,15-01-2019 00:00,05-01-2019,20190105,20190105,20190124,USD,RV,1790.30,20190101,NAM4,0

In [942]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   business_code           50000 non-null  object
 1   cust_number             50000 non-null  object
 2   name_customer           50000 non-null  object
 3   clear_date              40000 non-null  object
 4   posting_date            50000 non-null  object
 5   document_create_date    50000 non-null  int64
 6   document_create_date.1  50000 non-null  int64
 7   due_in_date             50000 non-null  int64
 8   invoice_currency        50000 non-null  object
 9   document type           50000 non-null  object
 10  total_open_amount       50000 non-null  float64
 11  baseline_create_date    50000 non-null  int64
 12  cust_payment_terms      50000 non-null  object
 13  isOpen                  50000 non-null  int64
dtypes: float64(1), int64(5), object(8)
memory usage: 5.3+ MB

<h3>Datetime conversion

In [943]:
data['clear_date']= pd.to_datetime(data['clear_date'])
data['posting_date']= pd.to_datetime(data['posting_date'])

C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22-07-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14-09-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13-11-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20-09-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '20-02-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17-10-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-04-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23-04-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25-10-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-11-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21-08-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17-07-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14-01-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22-09-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-06-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23-01-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17-06-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22-02-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17-02-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18-01-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24-07-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18-02-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28-08-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16-07-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-03-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30-06-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '26-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '14-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19-08-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '24-01-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27-03-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13-06-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28-02-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '16-04-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29-09-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22-08-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28-07-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25-11-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '23-07-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '18-06-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21-09-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21-02-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '15-05-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '27-09-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '21-02-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19-03-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25-06-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '29-03-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '30-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '28-03-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19-07-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '19-06-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '22-02-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '31-01-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25-04-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '25-05-2019' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
C:\src\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '17-01-2020' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)

In [944]:
data['document_create_date']= pd.to_datetime(data['document_create_date'],format='%Y%m%d')
data['document_create_date.1']= pd.to_datetime(data['document_create_date.1'],format='%Y%m%d')
data['due_in_date']= pd.to_datetime(data['due_in_date'],format='%Y%m%d')
data['baseline_create_date']= pd.to_datetime(data['baseline_create_date'],format='%Y%m%d')

In [945]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   business_code           50000 non-null  object
 1   cust_number             50000 non-null  object
 2   name_customer           50000 non-null  object
 3   clear_date              40000 non-null  datetime64[ns]
 4   posting_date            50000 non-null  datetime64[ns]
 5   document_create_date    50000 non-null  datetime64[ns]
 6   document_create_date.1  50000 non-null  datetime64[ns]
 7   due_in_date             50000 non-null  datetime64[ns]
 8   invoice_currency        50000 non-null  object
 9   document type           50000 non-null  object
 10  total_open_amount       50000 non-null  float64
 11  baseline_create_date    50000 non-null  datetime64[ns]
 12  cust_payment_terms      50000 non-null  object
 13  isOpen                  50000 non-null  int64
dtypes: datetime64[ns](6), float64(1), int64(1), object(6)
memory usage: 5.3+ MB

In [946]:
data

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,total_open_amount,baseline_create_date,cust_payment_terms,isOpen
0,U001,200769623,WAL-MAR corp,2020-11-02,2020-01-26,2020-01-25,2020-01-26,2020-02-10,USD,RV,54273.28,2020-01-26,NAH4,0
1,U001,200980828,BEN E,2019-08-08,2019-07-22,2019-07-22,2019-07-22,2019-08-11,USD,RV,79656.60,2019-07-22,NAD1,0
2,U001,200792734,MDV/ trust,2019-12-30,2019-09-14,2019-09-14,2019-09-14,2019-09-29,USD,RV,2253.86,2019-09-14,NAA8,0
3,CA02,140105686,SYSC llc,NaT,2020-03-30,2020-03-30,2020-03-30,2020-04-10,CAD,RV,3299.70,2020-03-31,CA10,1
4,U001,200769623,WAL-MAR foundation,2019-11-25,2019-11-13,2019-11-13,2019-11-13,2019-11-28,USD,RV,33133.29,2019-11-13,NAH4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U001,200561861,CO corporation,NaT,2020-04-21,2020-04-17,2020-04-21,2020-05-06,USD,RV,3187.86,2020-04-21,NAA8,1
49996,U001,200769623,WAL-MAR co,2019-03-09,2019-08-15,2019-08-14,2019-08-15,2019-08-30,USD,RV,6766.54,2019-08-15,NAH4,0
49997,U001,200772595,SAFEW associates,2020-05-03,2020-02-19,2020-02-18,2020-02-19,2020-03-05,USD,RV,6120.86,2020-02-19,NAA8,0
49998,U001,200726979,BJ'S llc,2019-12-12,2019-11-27,2019-11-26,2019-11-27,2019-12-12,USD,RV,63.48,2019-11-27,NAA8,0
49999,U001,200020431,DEC corp,2019-01-15,2019-05-01,2019-01-05,2019-01-05,2019-01-24,USD,RV,1790.30,2019-01-01,NAM4,0

<h3>Currency Conversion to USDR

In [947]:
rate_cad = .75

In [948]:
# convert couurency
data.replace({"invoice_currency": {"USD": 1, "CAD": rate_cad}}, inplace=True)
ls = data['total_open_amount']*data['invoice_currency']
data['total_open_amount'] = ls

In [949]:
data

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,document_create_date.1,due_in_date,invoice_currency,document type,total_open_amount,baseline_create_date,cust_payment_terms,isOpen
0,U001,200769623,WAL-MAR corp,2020-11-02,2020-01-26,2020-01-25,2020-01-26,2020-02-10,1.00,RV,54273.280,2020-01-26,NAH4,0
1,U001,200980828,BEN E,2019-08-08,2019-07-22,2019-07-22,2019-07-22,2019-08-11,1.00,RV,79656.600,2019-07-22,NAD1,0
2,U001,200792734,MDV/ trust,2019-12-30,2019-09-14,2019-09-14,2019-09-14,2019-09-29,1.00,RV,2253.860,2019-09-14,NAA8,0
3,CA02,140105686,SYSC llc,NaT,2020-03-30,2020-03-30,2020-03-30,2020-04-10,0.75,RV,2474.775,2020-03-31,CA10,1
4,U001,200769623,WAL-MAR foundation,2019-11-25,2019-11-13,2019-11-13,2019-11-13,2019-11-28,1.00,RV,33133.290,2019-11-13,NAH4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U001,200561861,CO corporation,NaT,2020-04-21,2020-04-17,2020-04-21,2020-05-06,1.00,RV,3187.860,2020-04-21,NAA8,1
49996,U001,200769623,WAL-MAR co,2019-03-09,2019-08-15,2019-08-14,2019-08-15,2019-08-30,1.00,RV,6766.540,2019-08-15,NAH4,0
49997,U001,200772595,SAFEW associates,2020-05-03,2020-02-19,2020-02-18,2020-02-19,2020-03-05,1.00,RV,6120.860,2020-02-19,NAA8,0
49998,U001,200726979,BJ'S llc,2019-12-12,2019-11-27,2019-11-26,2019-11-27,2019-12-12,1.00,RV,63.480,2019-11-27,NAA8,0
49999,U001,200020431,DEC corp,2019-01-15,2019-05-01,2019-01-05,2019-01-05,2019-01-24,1.00,RV,1790.300,2019-01-01,NAM4,0

In [950]:
data.drop(['invoice_currency'],axis=1,inplace=True)
data.drop(['document_create_date.1'],axis=1,inplace=True)

In [951]:
data

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,due_in_date,document type,total_open_amount,baseline_create_date,cust_payment_terms,isOpen
0,U001,200769623,WAL-MAR corp,2020-11-02,2020-01-26,2020-01-25,2020-02-10,RV,54273.280,2020-01-26,NAH4,0
1,U001,200980828,BEN E,2019-08-08,2019-07-22,2019-07-22,2019-08-11,RV,79656.600,2019-07-22,NAD1,0
2,U001,200792734,MDV/ trust,2019-12-30,2019-09-14,2019-09-14,2019-09-29,RV,2253.860,2019-09-14,NAA8,0
3,CA02,140105686,SYSC llc,NaT,2020-03-30,2020-03-30,2020-04-10,RV,2474.775,2020-03-31,CA10,1
4,U001,200769623,WAL-MAR foundation,2019-11-25,2019-11-13,2019-11-13,2019-11-28,RV,33133.290,2019-11-13,NAH4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U001,200561861,CO corporation,NaT,2020-04-21,2020-04-17,2020-05-06,RV,3187.860,2020-04-21,NAA8,1
49996,U001,200769623,WAL-MAR co,2019-03-09,2019-08-15,2019-08-14,2019-08-30,RV,6766.540,2019-08-15,NAH4,0
49997,U001,200772595,SAFEW associates,2020-05-03,2020-02-19,2020-02-18,2020-03-05,RV,6120.860,2020-02-19,NAA8,0
49998,U001,200726979,BJ'S llc,2019-12-12,2019-11-27,2019-11-26,2019-12-12,RV,63.480,2019-11-27,NAA8,0
49999,U001,200020431,DEC corp,2019-01-15,2019-05-01,2019-01-05,2019-01-24,RV,1790.300,2019-01-01,NAM4,0

<h3>Seperation of months, days, WeekDays

In [952]:
data['due_day'] = data.due_in_date.dt.day
data['due_month'] = data.due_in_date.dt.month
data['document_create_date_day'] = data.document_create_date.dt.day
data['document_create_date_month'] = data.document_create_date.dt.month
data['clear_date_day'] = data.clear_date.dt.day
data['clear_date_month'] = data.clear_date.dt.month
data['due_week_day'] = data.due_in_date.dt.dayofweek
data['clear_week_day'] = data.clear_date.dt.dayofweek

In [953]:
data

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,due_in_date,document type,total_open_amount,baseline_create_date,cust_payment_terms,isOpen,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day
0,U001,200769623,WAL-MAR corp,2020-11-02,2020-01-26,2020-01-25,2020-02-10,RV,54273.280,2020-01-26,NAH4,0,10,2,25,1,2.0,11.0,0,0.0
1,U001,200980828,BEN E,2019-08-08,2019-07-22,2019-07-22,2019-08-11,RV,79656.600,2019-07-22,NAD1,0,11,8,22,7,8.0,8.0,6,3.0
2,U001,200792734,MDV/ trust,2019-12-30,2019-09-14,2019-09-14,2019-09-29,RV,2253.860,2019-09-14,NAA8,0,29,9,14,9,30.0,12.0,6,0.0
3,CA02,140105686,SYSC llc,NaT,2020-03-30,2020-03-30,2020-04-10,RV,2474.775,2020-03-31,CA10,1,10,4,30,3,NaN,NaN,4,NaN
4,U001,200769623,WAL-MAR foundation,2019-11-25,2019-11-13,2019-11-13,2019-11-28,RV,33133.290,2019-11-13,NAH4,0,28,11,13,11,25.0,11.0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U001,200561861,CO corporation,NaT,2020-04-21,2020-04-17,2020-05-06,RV,3187.860,2020-04-21,NAA8,1,6,5,17,4,NaN,NaN,2,NaN
49996,U001,200769623,WAL-MAR co,2019-03-09,2019-08-15,2019-08-14,2019-08-30,RV,6766.540,2019-08-15,NAH4,0,30,8,14,8,9.0,3.0,4,5.0
49997,U001,200772595,SAFEW associates,2020-05-03,2020-02-19,2020-02-18,2020-03-05,RV,6120.860,2020-02-19,NAA8,0,5,3,18,2,3.0,5.0,3,6.0
49998,U001,200726979,BJ'S llc,2019-12-12,2019-11-27,2019-11-26,2019-12-12,RV,63.480,2019-11-27,NAA8,0,12,12,26,11,12.0,12.0,3,3.0
49999,U001,200020431,DEC corp,2019-01-15,2019-05-01,2019-01-05,2019-01-24,RV,1790.300,2019-01-01,NAM4,0,24,1,5,1,15.0,1.0,3,1.0

In [954]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               50000 non-null  object
 1   cust_number                 50000 non-null  object
 2   name_customer               50000 non-null  object
 3   clear_date                  40000 non-null  datetime64[ns]
 4   posting_date                50000 non-null  datetime64[ns]
 5   document_create_date        50000 non-null  datetime64[ns]
 6   due_in_date                 50000 non-null  datetime64[ns]
 7   document type               50000 non-null  object
 8   total_open_amount           50000 non-null  float64
 9   baseline_create_date        50000 non-null  datetime64[ns]
 10  cust_payment_terms          50000 non-null  object
 11  isOpen                      50000 non-null  int64
 12  due_day                     50000 non-null  int64
 13  due_month                   50000 non-null  int64
 14  document_create_date_day    50000 non-null  int64
 15  document_create_date_month  50000 non-null  int64
 16  clear_date_day              40000 non-null  float64
 17  clear_date_month            40000 non-null  float64
 18  due_week_day                50000 non-null  int64
 19  clear_week_day              40000 non-null  float64
dtypes: datetime64[ns](5), float64(4), int64(6), object(5)
memory usage: 7.6+ MB

<h3>Delay Date/Month Calculation

In [955]:
data['delay_day'] = data['clear_date']-data['due_in_date']
data.delay_day = data.delay_day.dt.days

In [956]:
temp1 = data['clear_date'].dt.month
temp2 = data['due_in_date'].dt.month
temp3 = temp1-temp2
data['delay_month'] = temp3

In [957]:
data['delay_day'].describe()

count    40000.000000
mean         1.872750
std         90.990873
min       -326.000000
25%         -5.000000
50%          0.000000
75%          6.000000
max        316.000000
Name: delay_day, dtype: float64

In [958]:
# data['delay_month_check'] = data['clear_date'].dt.to_period('M')-data['due_in_date'].dt.to_period('M')

In [959]:
type(data['delay_month'][1])

numpy.float64

In [960]:
data.sort_index()

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,due_in_date,document type,total_open_amount,baseline_create_date,...,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month
0,U001,200769623,WAL-MAR corp,2020-11-02,2020-01-26,2020-01-25,2020-02-10,RV,54273.280,2020-01-26,...,10,2,25,1,2.0,11.0,0,0.0,266.0,9.0
1,U001,200980828,BEN E,2019-08-08,2019-07-22,2019-07-22,2019-08-11,RV,79656.600,2019-07-22,...,11,8,22,7,8.0,8.0,6,3.0,-3.0,0.0
2,U001,200792734,MDV/ trust,2019-12-30,2019-09-14,2019-09-14,2019-09-29,RV,2253.860,2019-09-14,...,29,9,14,9,30.0,12.0,6,0.0,92.0,3.0
3,CA02,140105686,SYSC llc,NaT,2020-03-30,2020-03-30,2020-04-10,RV,2474.775,2020-03-31,...,10,4,30,3,NaN,NaN,4,NaN,NaN,NaN
4,U001,200769623,WAL-MAR foundation,2019-11-25,2019-11-13,2019-11-13,2019-11-28,RV,33133.290,2019-11-13,...,28,11,13,11,25.0,11.0,3,0.0,-3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U001,200561861,CO corporation,NaT,2020-04-21,2020-04-17,2020-05-06,RV,3187.860,2020-04-21,...,6,5,17,4,NaN,NaN,2,NaN,NaN,NaN
49996,U001,200769623,WAL-MAR co,2019-03-09,2019-08-15,2019-08-14,2019-08-30,RV,6766.540,2019-08-15,...,30,8,14,8,9.0,3.0,4,5.0,-174.0,-5.0
49997,U001,200772595,SAFEW associates,2020-05-03,2020-02-19,2020-02-18,2020-03-05,RV,6120.860,2020-02-19,...,5,3,18,2,3.0,5.0,3,6.0,59.0,2.0
49998,U001,200726979,BJ'S llc,2019-12-12,2019-11-27,2019-11-26,2019-12-12,RV,63.480,2019-11-27,...,12,12,26,11,12.0,12.0,3,3.0,0.0,0.0
49999,U001,200020431,DEC corp,2019-01-15,2019-05-01,2019-01-05,2019-01-24,RV,1790.300,2019-01-01,...,24,1,5,1,15.0,1.0,3,1.0,-9.0,0.0

In [961]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               50000 non-null  object
 1   cust_number                 50000 non-null  object
 2   name_customer               50000 non-null  object
 3   clear_date                  40000 non-null  datetime64[ns]
 4   posting_date                50000 non-null  datetime64[ns]
 5   document_create_date        50000 non-null  datetime64[ns]
 6   due_in_date                 50000 non-null  datetime64[ns]
 7   document type               50000 non-null  object
 8   total_open_amount           50000 non-null  float64
 9   baseline_create_date        50000 non-null  datetime64[ns]
 10  cust_payment_terms          50000 non-null  object
 11  isOpen                      50000 non-null  int64
 12  due_day                     50000 non-null  int64
 13  due_month                   50000 non-null  int64
 14  document_create_date_day    50000 non-null  int64
 15  document_create_date_month  50000 non-null  int64
 16  clear_date_day              40000 non-null  float64
 17  clear_date_month            40000 non-null  float64
 18  due_week_day                50000 non-null  int64
 19  clear_week_day              40000 non-null  float64
 20  delay_day                   40000 non-null  float64
 21  delay_month                 40000 non-null  float64
dtypes: datetime64[ns](5), float64(6), int64(6), object(5)
memory usage: 8.4+ MB

In [962]:
data.head()

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,due_in_date,document type,total_open_amount,baseline_create_date,...,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month
0,U001,200769623,WAL-MAR corp,2020-11-02,2020-01-26,2020-01-25,2020-02-10,RV,54273.280,2020-01-26,...,10,2,25,1,2.0,11.0,0,0.0,266.0,9.0
1,U001,200980828,BEN E,2019-08-08,2019-07-22,2019-07-22,2019-08-11,RV,79656.600,2019-07-22,...,11,8,22,7,8.0,8.0,6,3.0,-3.0,0.0
2,U001,200792734,MDV/ trust,2019-12-30,2019-09-14,2019-09-14,2019-09-29,RV,2253.860,2019-09-14,...,29,9,14,9,30.0,12.0,6,0.0,92.0,3.0
3,CA02,140105686,SYSC llc,NaT,2020-03-30,2020-03-30,2020-04-10,RV,2474.775,2020-03-31,...,10,4,30,3,NaN,NaN,4,NaN,NaN,NaN
4,U001,200769623,WAL-MAR foundation,2019-11-25,2019-11-13,2019-11-13,2019-11-28,RV,33133.290,2019-11-13,...,28,11,13,11,25.0,11.0,3,0.0,-3.0,0.0

In [976]:
data.dtypes

business_code                          int32
cust_number                            int32
name_customer                          int32
clear_date                    datetime64[ns]
posting_date                  datetime64[ns]
document_create_date          datetime64[ns]
due_in_date                   datetime64[ns]
document type                          int32
total_open_amount                    float64
baseline_create_date          datetime64[ns]
cust_payment_terms                    object
isOpen                                 int64
due_day                                int64
due_month                              int64
document_create_date_day               int64
document_create_date_month             int64
clear_date_day                       float64
clear_date_month                     float64
due_week_day                           int64
clear_week_day                       float64
delay_day                            float64
delay_month                          float64
payment_term_alpha                     int32
payment_term_num                       int64
dtype: object

In [981]:
data.drop(['document_create_date','baseline_create_date','posting_date','clear_date'],axis=1,inplace=True)

In [982]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               50000 non-null  int32
 1   cust_number                 50000 non-null  int32
 2   name_customer               50000 non-null  int32
 3   due_in_date                 50000 non-null  datetime64[ns]
 4   document type               50000 non-null  int32
 5   total_open_amount           50000 non-null  float64
 6   cust_payment_terms          50000 non-null  object
 7   isOpen                      50000 non-null  int64
 8   due_day                     50000 non-null  int64
 9   due_month                   50000 non-null  int64
 10  document_create_date_day    50000 non-null  int64
 11  document_create_date_month  50000 non-null  int64
 12  clear_date_day              40000 non-null  float64
 13  clear_date_month            40000 non-null  float64
 14  due_week_day                50000 non-null  int64
 15  clear_week_day              40000 non-null  float64
 16  delay_day                   40000 non-null  float64
 17  delay_month                 40000 non-null  float64
 18  payment_term_alpha          50000 non-null  int32
 19  payment_term_num            50000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(5), int64(7), object(1)
memory usage: 6.7+ MB

<h1>EDA

In [983]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               50000 non-null  int32
 1   cust_number                 50000 non-null  int32
 2   name_customer               50000 non-null  int32
 3   due_in_date                 50000 non-null  datetime64[ns]
 4   document type               50000 non-null  int32
 5   total_open_amount           50000 non-null  float64
 6   cust_payment_terms          50000 non-null  object
 7   isOpen                      50000 non-null  int64
 8   due_day                     50000 non-null  int64
 9   due_month                   50000 non-null  int64
 10  document_create_date_day    50000 non-null  int64
 11  document_create_date_month  50000 non-null  int64
 12  clear_date_day              40000 non-null  float64
 13  clear_date_month            40000 non-null  float64
 14  due_week_day                50000 non-null  int64
 15  clear_week_day              40000 non-null  float64
 16  delay_day                   40000 non-null  float64
 17  delay_month                 40000 non-null  float64
 18  payment_term_alpha          50000 non-null  int32
 19  payment_term_num            50000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int32(5), int64(7), object(1)
memory usage: 6.7+ MB

In [984]:
data.nunique()

business_code                     6
cust_number                    1099
name_customer                  4197
due_in_date                     547
document type                     2
total_open_amount             44370
cust_payment_terms               74
isOpen                            2
due_day                          31
due_month                        12
document_create_date_day         31
document_create_date_month       12
clear_date_day                   31
clear_date_month                 12
due_week_day                      7
clear_week_day                    7
delay_day                       595
delay_month                      23
payment_term_alpha               54
payment_term_num                 24
dtype: int64

In [985]:
data.corr()

,business_code,cust_number,name_customer,document type,total_open_amount,isOpen,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month,payment_term_alpha,payment_term_num
business_code,1.000000,0.134011,-0.025660,-0.020650,-0.068789,-0.012852,0.002628,0.008231,0.005160,-0.011120,0.024111,0.010436,-0.035129,0.002677,0.008669,0.008836,0.435668,-0.220587
cust_number,0.134011,1.000000,0.211708,-0.019041,-0.038578,0.001349,0.001248,0.000060,0.015391,0.004720,0.027422,-0.005090,-0.016011,-0.000122,-0.005029,-0.008042,0.303798,-0.189577
name_customer,-0.025660,0.211708,1.000000,0.006378,-0.021059,-0.002858,-0.005240,0.005119,0.002895,0.010218,-0.002931,0.026264,0.013088,-0.023135,0.025460,0.022897,0.156821,-0.067626
document type,-0.020650,-0.019041,0.006378,1.000000,-0.008331,-0.005478,-0.004199,-0.010934,0.016746,-0.007700,-0.009124,-0.006008,0.005398,-0.002314,0.007488,0.007391,-0.014276,0.008142
total_open_amount,-0.068789,-0.038578,-0.021059,-0.008331,1.000000,0.014759,-0.008740,0.022790,0.014299,0.022892,0.003100,0.027933,0.001784,0.010193,-0.001828,-0.003593,-0.165880,0.107075
isOpen,-0.012852,0.001349,-0.002858,-0.005478,0.014759,1.000000,-0.000217,-0.256739,-0.019178,-0.271570,NaN,NaN,-0.000672,NaN,NaN,NaN,-0.016453,-0.011994
due_day,0.002628,0.001248,-0.005240,-0.004199,-0.008740,-0.000217,1.000000,-0.053400,-0.388666,0.048255,0.553845,-0.021960,-0.005540,-0.164652,0.002593,0.021026,0.006977,-0.016867
due_month,0.008231,0.000060,0.005119,-0.010934,0.022790,-0.256739,-0.053400,1.000000,0.030752,0.908803,0.102689,0.606919,-0.007632,0.029006,-0.396089,-0.416156,0.024846,0.004062
document_create_date_day,0.005160,0.015391,0.002895,0.016746,0.014299,-0.019178,-0.388666,0.030752,1.000000,-0.034016,-0.384123,0.113323,0.008951,0.148025,0.103522,0.104687,0.002150,-0.002673
document_create_date_month,-0.011120,0.004720,0.010218,-0.007700,0.022892,-0.271570,0.048255,0.908803,-0.034016,1.000000,0.181554,0.579615,-0.033524,-0.011063,-0.374071,-0.341210,0.004258,0.016283
clear_date_day,0.024111,0.027422,-0.002931,-0.009124,0.003100,NaN,0.553845,0.102689,-0.384123,0.181554,1.000000,-0.055240,0.006942,-0.211366,-0.164829,-0.177241,0.026540,-0.007811
clear_date_month,0.010436,-0.005090,0.026264,-0.006008,0.027933,NaN,-0.021960,0.606919,0.113323,0.579615,-0.055240,1.000000,-0.019102,0.054864,0.461519,0.470100,-0.002781,0.010811
due_week_day,-0.035129,-0.016011,0.013088,0.005398,0.001784,-0.000672,-0.005540,-0.007632,0.008951,-0.033524,0.006942,-0.019102,1.000000,-0.036643,-0.010873,-0.009531,-0.037877,0.033562
clear_week_day,0.002677,-0.000122,-0.023135,-0.002314,0.010193,NaN,-0.164652,0.029006,0.148025,-0.011063,-0.211366,0.054864,-0.036643,1.000000,0.036441,0.030558,0.001182,-0.008932
delay_day,0.008669,-0.005029,0.025460,0.007488,-0.001828,NaN,0.002593,-0.396089,0.103522,-0.374071,-0.164829,0.461519,-0.010873,0.036441,1.000000,0.967896,-0.032740,0.007563
delay_month,0.008836,-0.008042,0.022897,0.007391,-0.003593,NaN,0.021026,-0.416156,0.104687,-0.341210,-0.177241,0.470100,-0.009531,0.030558,0.967896,1.000000,-0.028207,0.008389
payment_term_alpha,0.435668,0.303798,0.156821,-0.014276,-0.165880,-0.016453,0.006977,0.024846,0.002150,0.004258,0.026540,-0.002781,-0.037877,0.001182,-0.032740,-0.028207,1.000000,-0.521038
payment_term_num,-0.220587,-0.189577,-0.067626,0.008142,0.107075,-0.011994,-0.016867,0.004062,-0.002673,0.016283,-0.007811,0.010811,0.033562,-0.008932,0.007563,0.008389,-0.521038,1.000000

In [986]:
data.kurt()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_16840\2907027414.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.kurt()

business_code                   41.103920
cust_number                      1.841028
name_customer                   -1.445874
document type                 8329.166467
total_open_amount               13.258850
isOpen                           0.250145
due_day                         -1.177511
due_month                       -0.947921
document_create_date_day        -1.225914
document_create_date_month      -0.929031
clear_date_day                  -1.267810
clear_date_month                -1.294394
due_week_day                    -1.138522
clear_week_day                  -0.895365
delay_day                        2.881408
delay_month                      2.911784
payment_term_alpha               2.368367
payment_term_num                88.620557
dtype: float64

In [987]:
data.describe()

,business_code,cust_number,name_customer,document type,total_open_amount,isOpen,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month,payment_term_alpha,payment_term_num
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,40000.000000,40000.000000,50000.000000,40000.000000,40000.000000,40000.000000,50000.000000,50000.000000
mean,0.970940,797.332460,2549.461380,0.000120,31234.600026,0.200000,15.980960,5.731140,15.487060,5.303200,15.975125,6.257175,3.068740,2.326925,1.872750,0.110450,15.818180,6.291780
std,0.515112,218.729319,1416.297976,0.010954,36688.217267,0.400004,8.647521,3.237441,8.839939,3.276725,8.916706,3.582647,1.890134,1.730555,90.990873,3.131397,9.836553,4.989419
min,0.000000,0.000000,0.000000,0.000000,0.720000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,-326.000000,-11.000000,0.000000,0.000000
25%,1.000000,753.000000,1011.000000,0.000000,4787.135000,0.000000,9.000000,3.000000,8.000000,3.000000,8.000000,3.000000,1.000000,1.000000,-5.000000,0.000000,9.000000,4.000000
50%,1.000000,891.000000,2934.500000,0.000000,17317.975000,0.000000,16.000000,5.000000,15.000000,4.000000,16.000000,6.000000,3.000000,2.000000,0.000000,0.000000,9.000000,8.000000
75%,1.000000,908.000000,4062.000000,0.000000,46216.070000,0.000000,24.000000,8.000000,23.000000,8.000000,24.000000,9.000000,5.000000,4.000000,6.000000,0.000000,23.000000,8.000000
max,5.000000,1098.000000,4196.000000,1.000000,668593.360000,1.000000,31.000000,12.000000,31.000000,12.000000,31.000000,12.000000,6.000000,6.000000,316.000000,11.000000,53.000000,129.000000

<h4>Custnumber Payment Term Number Engineering

In [988]:
data['cust_payment_terms'].unique()

array(['NAH4', 'NAD1', 'NAA8', 'CA10', 'NAC6', 'NAM2', 'NAAX', 'NAVE',
       'NAG2', 'NABG', 'NAM4', 'NA10', 'NAU5', 'NA32', 'NAD5', 'NAWP',
       'NAGD', 'NAVR', 'CA30', 'NAM1', 'NAAW', 'NAVF', 'NAD4', 'NAUZ',
       'NA3F', 'NAX2', 'NAVQ', 'NATM', 'CAB1', 'NA84', 'NAWM', 'NACB',
       'NACG', 'NA38', 'NAWN', 'C106', 'NAWU', 'NAB1', 'NA3B', 'NA9X',
       'NAVD', 'NAVM', 'NACE', 'NA25', 'NAUP', 'NAM3', 'NACH', 'CAX2',
       'NATV', 'NAVL', 'NATZ', 'C129', 'BR56', 'NA31', 'NATW', 'B052',
       'NAV2', 'NATX', 'NAUY', 'NA8Q', 'NATJ', 'BR12', 'NATU', '90M7',
       'NAV9', 'NATK', 'CA60', 'NATL', 'NAD8', 'NAUW', 'NAVC', 'NABD',
       'NATH', 'MC15'], dtype=object)

In [989]:
temp = data[:20]

In [990]:
import re
def extract_alpha_num(df):
    def segg(alpha_num):
        alpha = re.findall(r'\D+', alpha_num)
        num = re.findall(r'\d+', alpha_num)
        alpha = alpha[0]
        alpha = "".join(alpha)
        if len(num)>0:
            num = int(num[0])
        else:
            num = 0
        return pd.Series(
            (alpha,num),
            index = ['payment_term_alpha','payment_term_num']
        )

    sep = df['cust_payment_terms'].apply(segg)
    df[sep.columns] = sep
    
extract_alpha_num(data)

In [991]:
data

,business_code,cust_number,name_customer,due_in_date,document type,total_open_amount,cust_payment_terms,isOpen,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month,payment_term_alpha,payment_term_num
0,1,908,4065,2020-02-10,0,54273.280,NAH4,0,10,2,25,1,2.0,11.0,0,0.0,266.0,9.0,NAH,4
1,1,1072,385,2019-08-11,0,79656.600,NAD1,0,11,8,22,7,8.0,8.0,6,3.0,-3.0,0.0,NAD,1
2,1,977,2537,2019-09-29,0,2253.860,NAA8,0,29,9,14,9,30.0,12.0,6,0.0,92.0,3.0,NAA,8
3,0,435,3689,2020-04-10,0,2474.775,CA10,1,10,4,30,3,NaN,NaN,4,NaN,NaN,NaN,CA,10
4,1,908,4067,2019-11-28,0,33133.290,NAH4,0,28,11,13,11,25.0,11.0,3,0.0,-3.0,0.0,NAH,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1,691,742,2020-05-06,0,3187.860,NAA8,1,6,5,17,4,NaN,NaN,2,NaN,NaN,NaN,NAA,8
49996,1,908,4064,2019-08-30,0,6766.540,NAH4,0,30,8,14,8,9.0,3.0,4,5.0,-174.0,-5.0,NAH,4
49997,1,913,3277,2020-03-05,0,6120.860,NAA8,0,5,3,18,2,3.0,5.0,3,6.0,59.0,2.0,NAA,8
49998,1,806,432,2019-12-12,0,63.480,NAA8,0,12,12,26,11,12.0,12.0,3,3.0,0.0,0.0,NAA,8
49999,1,485,981,2019-01-24,0,1790.300,NAM4,0,24,1,5,1,15.0,1.0,3,1.0,-9.0,0.0,NAM,4

In [992]:
data.dtypes

business_code                          int32
cust_number                            int32
name_customer                          int32
due_in_date                   datetime64[ns]
document type                          int32
total_open_amount                    float64
cust_payment_terms                    object
isOpen                                 int64
due_day                                int64
due_month                              int64
document_create_date_day               int64
document_create_date_month             int64
clear_date_day                       float64
clear_date_month                     float64
due_week_day                           int64
clear_week_day                       float64
delay_day                            float64
delay_month                          float64
payment_term_alpha                    object
payment_term_num                       int64
dtype: object

In [993]:
data.nunique()

business_code                     6
cust_number                    1099
name_customer                  4197
due_in_date                     547
document type                     2
total_open_amount             44370
cust_payment_terms               74
isOpen                            2
due_day                          31
due_month                        12
document_create_date_day         31
document_create_date_month       12
clear_date_day                   31
clear_date_month                 12
due_week_day                      7
clear_week_day                    7
delay_day                       595
delay_month                      23
payment_term_alpha               54
payment_term_num                 24
dtype: int64

<h2>Encoding
<h4>Label Encoding used here

In [994]:
le = preprocessing.LabelEncoder()
data['business_code'] = le.fit_transform(data['business_code'])
data['cust_number'] = le.fit_transform(data['cust_number'])
data['name_customer'] = le.fit_transform(data['name_customer'])
data['payment_term_alpha'] = le.fit_transform(data['payment_term_alpha'])
data['document type'] = le.fit_transform(data['document type'])

In [995]:
data.nunique()

business_code                     6
cust_number                    1099
name_customer                  4197
due_in_date                     547
document type                     2
total_open_amount             44370
cust_payment_terms               74
isOpen                            2
due_day                          31
due_month                        12
document_create_date_day         31
document_create_date_month       12
clear_date_day                   31
clear_date_month                 12
due_week_day                      7
clear_week_day                    7
delay_day                       595
delay_month                      23
payment_term_alpha               54
payment_term_num                 24
dtype: int64

In [998]:
data.dtypes

business_code                          int64
cust_number                            int64
name_customer                          int64
due_in_date                   datetime64[ns]
document type                          int64
total_open_amount                    float64
cust_payment_terms                    object
isOpen                                 int64
due_day                                int64
due_month                              int64
document_create_date_day               int64
document_create_date_month             int64
clear_date_day                       float64
clear_date_month                     float64
due_week_day                           int64
clear_week_day                       float64
delay_day                            float64
delay_month                          float64
payment_term_alpha                     int32
payment_term_num                       int64
dtype: object

In [ ]:
data.head()

,business_code,cust_number,name_customer,clear_date,posting_date,document_create_date,document_create_date.1,due_in_date,document type,total_open_amount,baseline_create_date,cust_payment_terms,isOpen,delay_day,delay_month,payment_term_alpha,payment_term_num
0,1,908,4065,2020-11-02,2020-01-26,2020-01-25,2020-01-26,2020-02-10,0,54273.280,2020-01-26,NAH4,0,266.0,9.0,23,4
1,1,1072,385,2019-08-08,2019-07-22,2019-07-22,2019-07-22,2019-08-11,0,79656.600,2019-07-22,NAD1,0,-3.0,0.0,20,1
2,1,977,2537,2019-12-30,2019-09-14,2019-09-14,2019-09-14,2019-09-29,0,2253.860,2019-09-14,NAA8,0,92.0,3.0,9,8
3,0,435,3689,NaT,2020-03-30,2020-03-30,2020-03-30,2020-04-10,0,2474.775,2020-03-31,CA10,1,NaN,NaN,3,10
4,1,908,4067,2019-11-25,2019-11-13,2019-11-13,2019-11-13,2019-11-28,0,33133.290,2019-11-13,NAH4,0,-3.0,0.0,23,4

In [999]:
data['payment_term_new'] =(data['payment_term_alpha'].astype(str)+data['payment_term_num'].astype(str)).astype(int)

In [1000]:
data.head()

,business_code,cust_number,name_customer,due_in_date,document type,total_open_amount,cust_payment_terms,isOpen,due_day,due_month,...,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month,payment_term_alpha,payment_term_num,payment_term_new
0,1,908,4065,2020-02-10,0,54273.280,NAH4,0,10,2,...,1,2.0,11.0,0,0.0,266.0,9.0,23,4,234
1,1,1072,385,2019-08-11,0,79656.600,NAD1,0,11,8,...,7,8.0,8.0,6,3.0,-3.0,0.0,20,1,201
2,1,977,2537,2019-09-29,0,2253.860,NAA8,0,29,9,...,9,30.0,12.0,6,0.0,92.0,3.0,9,8,98
3,0,435,3689,2020-04-10,0,2474.775,CA10,1,10,4,...,3,NaN,NaN,4,NaN,NaN,NaN,3,10,310
4,1,908,4067,2019-11-28,0,33133.290,NAH4,0,28,11,...,11,25.0,11.0,3,0.0,-3.0,0.0,23,4,234

In [1001]:
data.drop(['payment_term_alpha','payment_term_num','cust_payment_terms'],axis=1,inplace=True)

In [1002]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               50000 non-null  int64
 1   cust_number                 50000 non-null  int64
 2   name_customer               50000 non-null  int64
 3   due_in_date                 50000 non-null  datetime64[ns]
 4   document type               50000 non-null  int64
 5   total_open_amount           50000 non-null  float64
 6   isOpen                      50000 non-null  int64
 7   due_day                     50000 non-null  int64
 8   due_month                   50000 non-null  int64
 9   document_create_date_day    50000 non-null  int64
 10  document_create_date_month  50000 non-null  int64
 11  clear_date_day              40000 non-null  float64
 12  clear_date_month            40000 non-null  float64
 13  due_week_day                50000 non-null  int64
 14  clear_week_day              40000 non-null  float64
 15  delay_day                   40000 non-null  float64
 16  delay_month                 40000 non-null  float64
 17  payment_term_new            50000 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), int64(10)
memory usage: 6.7 MB

In [1003]:
data.dtypes

business_code                          int64
cust_number                            int64
name_customer                          int64
due_in_date                   datetime64[ns]
document type                          int64
total_open_amount                    float64
isOpen                                 int64
due_day                                int64
due_month                              int64
document_create_date_day               int64
document_create_date_month             int64
clear_date_day                       float64
clear_date_month                     float64
due_week_day                           int64
clear_week_day                       float64
delay_day                            float64
delay_month                          float64
payment_term_new                       int32
dtype: object

In [1004]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               50000 non-null  int64
 1   cust_number                 50000 non-null  int64
 2   name_customer               50000 non-null  int64
 3   due_in_date                 50000 non-null  datetime64[ns]
 4   document type               50000 non-null  int64
 5   total_open_amount           50000 non-null  float64
 6   isOpen                      50000 non-null  int64
 7   due_day                     50000 non-null  int64
 8   due_month                   50000 non-null  int64
 9   document_create_date_day    50000 non-null  int64
 10  document_create_date_month  50000 non-null  int64
 11  clear_date_day              40000 non-null  float64
 12  clear_date_month            40000 non-null  float64
 13  due_week_day                50000 non-null  int64
 14  clear_week_day              40000 non-null  float64
 15  delay_day                   40000 non-null  float64
 16  delay_month                 40000 non-null  float64
 17  payment_term_new            50000 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), int64(10)
memory usage: 6.7 MB

In [1005]:
data.nunique()

business_code                     6
cust_number                    1099
name_customer                  4197
due_in_date                     547
document type                     2
total_open_amount             44370
isOpen                            2
due_day                          31
due_month                        12
document_create_date_day         31
document_create_date_month       12
clear_date_day                   31
clear_date_month                 12
due_week_day                      7
clear_week_day                    7
delay_day                       595
delay_month                      23
payment_term_new                 68
dtype: int64

In [1006]:
data.corr()

,business_code,cust_number,name_customer,document type,total_open_amount,isOpen,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month,payment_term_new
business_code,1.000000,0.134011,-0.025660,-0.020650,-0.068789,-0.012852,0.002628,0.008231,0.005160,-0.011120,0.024111,0.010436,-0.035129,0.002677,0.008669,0.008836,0.036882
cust_number,0.134011,1.000000,0.211708,-0.019041,-0.038578,0.001349,0.001248,0.000060,0.015391,0.004720,0.027422,-0.005090,-0.016011,-0.000122,-0.005029,-0.008042,-0.108113
name_customer,-0.025660,0.211708,1.000000,0.006378,-0.021059,-0.002858,-0.005240,0.005119,0.002895,0.010218,-0.002931,0.026264,0.013088,-0.023135,0.025460,0.022897,0.081179
document type,-0.020650,-0.019041,0.006378,1.000000,-0.008331,-0.005478,-0.004199,-0.010934,0.016746,-0.007700,-0.009124,-0.006008,0.005398,-0.002314,0.007488,0.007391,0.008423
total_open_amount,-0.068789,-0.038578,-0.021059,-0.008331,1.000000,0.014759,-0.008740,0.022790,0.014299,0.022892,0.003100,0.027933,0.001784,0.010193,-0.001828,-0.003593,-0.077385
isOpen,-0.012852,0.001349,-0.002858,-0.005478,0.014759,1.000000,-0.000217,-0.256739,-0.019178,-0.271570,NaN,NaN,-0.000672,NaN,NaN,NaN,-0.038251
due_day,0.002628,0.001248,-0.005240,-0.004199,-0.008740,-0.000217,1.000000,-0.053400,-0.388666,0.048255,0.553845,-0.021960,-0.005540,-0.164652,0.002593,0.021026,-0.011739
due_month,0.008231,0.000060,0.005119,-0.010934,0.022790,-0.256739,-0.053400,1.000000,0.030752,0.908803,0.102689,0.606919,-0.007632,0.029006,-0.396089,-0.416156,0.030719
document_create_date_day,0.005160,0.015391,0.002895,0.016746,0.014299,-0.019178,-0.388666,0.030752,1.000000,-0.034016,-0.384123,0.113323,0.008951,0.148025,0.103522,0.104687,-0.004914
document_create_date_month,-0.011120,0.004720,0.010218,-0.007700,0.022892,-0.271570,0.048255,0.908803,-0.034016,1.000000,0.181554,0.579615,-0.033524,-0.011063,-0.374071,-0.341210,0.012978
clear_date_day,0.024111,0.027422,-0.002931,-0.009124,0.003100,NaN,0.553845,0.102689,-0.384123,0.181554,1.000000,-0.055240,0.006942,-0.211366,-0.164829,-0.177241,0.020189
clear_date_month,0.010436,-0.005090,0.026264,-0.006008,0.027933,NaN,-0.021960,0.606919,0.113323,0.579615,-0.055240,1.000000,-0.019102,0.054864,0.461519,0.470100,0.017178
due_week_day,-0.035129,-0.016011,0.013088,0.005398,0.001784,-0.000672,-0.005540,-0.007632,0.008951,-0.033524,0.006942,-0.019102,1.000000,-0.036643,-0.010873,-0.009531,0.014830
clear_week_day,0.002677,-0.000122,-0.023135,-0.002314,0.010193,NaN,-0.164652,0.029006,0.148025,-0.011063,-0.211366,0.054864,-0.036643,1.000000,0.036441,0.030558,0.002998
delay_day,0.008669,-0.005029,0.025460,0.007488,-0.001828,NaN,0.002593,-0.396089,0.103522,-0.374071,-0.164829,0.461519,-0.010873,0.036441,1.000000,0.967896,-0.009942
delay_month,0.008836,-0.008042,0.022897,0.007391,-0.003593,NaN,0.021026,-0.416156,0.104687,-0.341210,-0.177241,0.470100,-0.009531,0.030558,0.967896,1.000000,-0.007605
payment_term_new,0.036882,-0.108113,0.081179,0.008423,-0.077385,-0.038251,-0.011739,0.030719,-0.004914,0.012978,0.020189,0.017178,0.014830,0.002998,-0.009942,-0.007605,1.000000

In [1007]:
data.kurt()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_16840\2907027414.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.kurt()

business_code                   41.103920
cust_number                      1.841028
name_customer                   -1.445874
document type                 8329.166467
total_open_amount               13.258850
isOpen                           0.250145
due_day                         -1.177511
due_month                       -0.947921
document_create_date_day        -1.225914
document_create_date_month      -0.929031
clear_date_day                  -1.267810
clear_date_month                -1.294394
due_week_day                    -1.138522
clear_week_day                  -0.895365
delay_day                        2.881408
delay_month                      2.911784
payment_term_new                17.000797
dtype: float64

In [1009]:
data.drop('document type',axis=1,inplace=True)

In [1010]:
data

,business_code,cust_number,name_customer,due_in_date,total_open_amount,isOpen,due_day,due_month,document_create_date_day,document_create_date_month,clear_date_day,clear_date_month,due_week_day,clear_week_day,delay_day,delay_month,payment_term_new
0,1,908,4065,2020-02-10,54273.280,0,10,2,25,1,2.0,11.0,0,0.0,266.0,9.0,234
1,1,1072,385,2019-08-11,79656.600,0,11,8,22,7,8.0,8.0,6,3.0,-3.0,0.0,201
2,1,977,2537,2019-09-29,2253.860,0,29,9,14,9,30.0,12.0,6,0.0,92.0,3.0,98
3,0,435,3689,2020-04-10,2474.775,1,10,4,30,3,NaN,NaN,4,NaN,NaN,NaN,310
4,1,908,4067,2019-11-28,33133.290,0,28,11,13,11,25.0,11.0,3,0.0,-3.0,0.0,234
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1,691,742,2020-05-06,3187.860,1,6,5,17,4,NaN,NaN,2,NaN,NaN,NaN,98
49996,1,908,4064,2019-08-30,6766.540,0,30,8,14,8,9.0,3.0,4,5.0,-174.0,-5.0,234
49997,1,913,3277,2020-03-05,6120.860,0,5,3,18,2,3.0,5.0,3,6.0,59.0,2.0,98
49998,1,806,432,2019-12-12,63.480,0,12,12,26,11,12.0,12.0,3,3.0,0.0,0.0,98
49999,1,485,981,2019-01-24,1790.300,0,24,1,5,1,15.0,1.0,3,1.0,-9.0,0.0,244

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   business_code           50000 non-null  int32
 1   cust_number             50000 non-null  int32
 2   name_customer           50000 non-null  int32
 3   clear_date              40000 non-null  datetime64[ns]
 4   posting_date            50000 non-null  datetime64[ns]
 5   document_create_date    50000 non-null  datetime64[ns]
 6   document_create_date.1  50000 non-null  datetime64[ns]
 7   due_in_date             50000 non-null  datetime64[ns]
 8   total_open_amount       50000 non-null  float64
 9   baseline_create_date    50000 non-null  datetime64[ns]
 10  isOpen                  50000 non-null  int64
 11  delay_day               40000 non-null  float64
 12  delay_month             40000 non-null  float64
 13  payment_term_new        50000 non-null  int32
 14  count                   50000 non-null  int64
dtypes: datetime64[ns](6), float64(3), int32(4), int64(2)
memory usage: 5.0 MB

<h1>Tuning My Model

In [1122]:
data.kurt()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_16840\2907027414.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  data.kurt()

business_code                 41.071358
cust_number                    1.832842
name_customer                 -1.446201
total_open_amount             13.462278
isOpen                         0.292609
due_day                       -1.176788
due_month                     -0.952476
document_create_date_day      -1.224797
document_create_date_month    -0.934236
clear_date_day                -1.266886
clear_date_month              -1.295111
due_week_day                  -1.138917
clear_week_day                -0.896727
delay_day                      2.889193
delay_month                    2.919527
payment_term_new              16.618416
dtype: float64

<h1>Test Train Split

In [1031]:
data.drop_duplicates(inplace=True)

In [1032]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48833 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               48833 non-null  int64
 1   cust_number                 48833 non-null  int64
 2   name_customer               48833 non-null  int64
 3   due_in_date                 48833 non-null  datetime64[ns]
 4   total_open_amount           48833 non-null  float64
 5   isOpen                      48833 non-null  int64
 6   due_day                     48833 non-null  int64
 7   due_month                   48833 non-null  int64
 8   document_create_date_day    48833 non-null  int64
 9   document_create_date_month  48833 non-null  int64
 10  clear_date_day              39154 non-null  float64
 11  clear_date_month            39154 non-null  float64
 12  due_week_day                48833 non-null  int64
 13  clear_week_day              39154 non-null  float64
 14  delay_day                   39154 non-null  float64
 15  delay_month                 39154 non-null  float64
 16  payment_term_new            48833 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), int64(9)
memory usage: 6.5 MB

In [1043]:
test_data=data[data['clear_date_day'].isnull()]
test_data.shape

(9679, 17)

In [1044]:
train_data=data[data['clear_date_day'].notnull()]
train_data.shape

(39154, 17)

In [1047]:
train_data.drop('due_in_date',axis=1,inplace=True)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_16840\1045045491.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data.drop('due_in_date',axis=1,inplace=True)

In [1048]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39154 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   business_code               39154 non-null  int64
 1   cust_number                 39154 non-null  int64
 2   name_customer               39154 non-null  int64
 3   total_open_amount           39154 non-null  float64
 4   isOpen                      39154 non-null  int64
 5   due_day                     39154 non-null  int64
 6   due_month                   39154 non-null  int64
 7   document_create_date_day    39154 non-null  int64
 8   document_create_date_month  39154 non-null  int64
 9   clear_date_day              39154 non-null  float64
 10  clear_date_month            39154 non-null  float64
 11  due_week_day                39154 non-null  int64
 12  clear_week_day              39154 non-null  float64
 13  delay_day                   39154 non-null  float64
 14  delay_month                 39154 non-null  float64
 15  payment_term_new            39154 non-null  int32
dtypes: float64(6), int32(1), int64(9)
memory usage: 4.9 MB

In [1051]:
X = train_data.drop(['clear_date_day','clear_date_month','delay_day','delay_month'],axis=1)

In [1056]:
print(X.shape)
X.isnull().sum()

(39154, 12)

business_code                 0
cust_number                   0
name_customer                 0
total_open_amount             0
isOpen                        0
due_day                       0
due_month                     0
document_create_date_day      0
document_create_date_month    0
due_week_day                  0
clear_week_day                0
payment_term_new              0
dtype: int64

In [1087]:
y = train_data['delay_month']
print(y.shape)
y.isnull().sum()

(39154,)

0

In [1088]:
X_train, X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

In [1089]:
print(X_train.shape)
X_train.isnull().sum()

(31323, 12)

business_code                 0
cust_number                   0
name_customer                 0
total_open_amount             0
isOpen                        0
due_day                       0
due_month                     0
document_create_date_day      0
document_create_date_month    0
due_week_day                  0
clear_week_day                0
payment_term_new              0
dtype: int64

In [1090]:
print(X_test.shape)
X_test.isnull().sum()

(7831, 12)

business_code                 0
cust_number                   0
name_customer                 0
total_open_amount             0
isOpen                        0
due_day                       0
due_month                     0
document_create_date_day      0
document_create_date_month    0
due_week_day                  0
clear_week_day                0
payment_term_new              0
dtype: int64

In [1091]:
print(y_train.shape)
y_train.isnull().sum()

(31323,)

0

In [1092]:
print(y_test.shape)
y_test.isnull().sum()

(7831,)

0

In [1107]:
MSE_Score = []
R2_Score = []
Algorithm = []

In [1108]:
# Fitting Simple Linear Regression to the Training Set
Algorithm.append('Linear Regression')
clf = LinearRegression()
clf.fit(X_train, y_train)

# Predicting the Test Set Results
predicted = clf.predict(X_test)

In [1109]:
# Appending the Scores For Visualisation at a Later Part
MSE_Score.append(mean_squared_error(y_test, predicted,squared=False))
R2_Score.append(r2_score(y_test, predicted))

In [1110]:
# Fitting SVR to the Training Set
Algorithm.append('Support Vector Regression')
clf = SVR()
clf.fit(X_train, y_train)

# Predicting the Test Set Results
predicted = clf.predict(X_test)

In [1111]:
# Appending the Scores For Visualisation at a Later Part
MSE_Score.append(mean_squared_error(y_test, predicted,squared=False))
R2_Score.append(r2_score(y_test, predicted))

In [1112]:
# Fitting Decision Tree to the Training Set
Algorithm.append('Decision Tree Regressor')
clf = DecisionTreeRegressor()
clf.fit(X_train, y_train)

# Predicting the Test Set Results
predicted = clf.predict(X_test)

In [1113]:
# Appending the Scores For Visualisation at a Later Part
MSE_Score.append(mean_squared_error(y_test, predicted,squared=False))
R2_Score.append(r2_score(y_test, predicted))

In [1114]:
# Fitting Random Forest Regressor Tree to the Training Set
Algorithm.append('Random Forest Regressor')
clf = RandomForestRegressor()
clf.fit(X_train, y_train)

# Predicting the Test Set Results
predicted = clf.predict(X_test)

In [1115]:
# Appending the Scores For Visualisation at a Later Part
MSE_Score.append(mean_squared_error(y_test, predicted,squared=False))
R2_Score.append(r2_score(y_test, predicted))

In [1116]:
# Fitting XGBoost Regressor to the Training Set
Algorithm.append('XGB Regressor')
clf = xgb.XGBRegressor()
clf.fit(X_train, y_train)

# Predicting the Test Set Results
predicted = clf.predict(X_test)

C:\src\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

In [1117]:
# Appending the Scores For Visualisation at a Later Part
MSE_Score.append(mean_squared_error(y_test, predicted,squared=False))
R2_Score.append(r2_score(y_test, predicted))

In [1118]:
# Just Combining the Lists into a DataFrame for a Better Visualisation
Comparison = pd.DataFrame(list(zip(Algorithm, MSE_Score, R2_Score)), columns = ['Algorithm', 'RMSE_Score', 'R2_Score'])

In [1119]:
# Score Card
Comparison

                 Algorithm  RMSE_Score  R2_Score
0        Linear Regression    2.785317  0.190528
1  Decision Tree Regressor    2.007202  0.579627
2  Random Forest Regressor    1.410383  0.792448
3            XGB Regressor    1.575934  0.740863

In [1120]:
# data.to_csv('./f1.csv',index=False)